### ISSUE TITLE
Extra Recipies for Stonecutter [Suggestion]

### ISSUE THREAD

**Issue by SpiderKolo** [RahalaBytes/LottaTerracotta#1]
First of, I really like this mod. It looks cool, is very simple and have few cool features I would probably like to make use of.
It's just sad that we can't craft new items using Stonecutter.
Sure, Terracotta isn't technically a stone (it's a cooked Clay blocks which we can apply colors to), but it would be really nice to have Stonecutter being more useful for this block in general.

I did put same request for Concrete.

**Comment by Angela** [comment]
Hello @SpiderKolo! Thanks for your feedback. 

Stonecutter recipes for slabs, stairs, walls and vertical slabs have been added to the newest version.
