### ISSUE TITLE
[Visual Bug] Lacking Textures when you place Terracota Tiles one on another.

### ISSUE THREAD

**Issue by SpiderKolo** [RahalaBytes/LottaTerracotta#2]
Here is how it looks like.
![image](https://user-images.githubusercontent.com/62638498/82159647-fff1bf80-988f-11ea-9eb1-48e2759a8244.png)
![image](https://user-images.githubusercontent.com/62638498/82159663-2ca5d700-9890-11ea-9a6d-073568d189b4.png)

**Comment by Angela** [comment]
Thank you for your bug report! This issue should be fixed in v1.3.0 which was released today.

**Comment by SpiderKolo** [comment]
Wow... that was quick... sadly I just found another bug related to tiles so I'm posting it there.
It's a weird visual glitch this time on the side of the tile. As if pixels tried to fight which one should be visible:
![image](https://user-images.githubusercontent.com/62638498/82161694-2703bd80-989f-11ea-939c-b9847b0b27d7.png)
It's difficult to show this on picture, you have to place tiles and look into them in game.

**Comment by Angela** [comment]
@SpiderKolo thanks. I've opened a new issue for this bug [here](https://github.com/RahalaBytes/LottaTerracotta/issues/3)
