### ISSUE TITLE
Half slab stacking on other half slabs

### ISSUE THREAD

**Issue by chuck252** [RahalaBytes/LottaTerracotta#5]
When I try to stack a terracotta half slab on an oak slab, or any other slab, there is a gap. 

Same goes the other way, if I put down a half slab, and then a terracotta half slab on top there is a gap.

**Comment by chuck252** [comment]
Wasn't an issue, I'm just new to building detailed things.

**Comment by Angela** [comment]
Hey @chuck252, sounds like you might be trying to mix slabs of two different types? This isn't supported by default (as I think you realized) but there is a mod called [Double Slabs](https://www.curseforge.com/minecraft/mc-mods/double-slabs) that you could check out that allows this.
