### ISSUE TITLE
Latest CF build contains a SweetConcrete class, causing crashes

### ISSUE THREAD

**Issue by malte0811** [RahalaBytes/LottaTerracotta#6]
`lottaterracotta-1.18.2-1.4.jar` (latest build on CF) contains `org.villainy.sweetconcrete.helper.Shape`, which can cause strange crashes like [this](https://gist.github.com/brisingraerowing/f15260ab251f8c5e73fb48bf00a9eddd). I assume the class is either left over from debugging or it's some really weird build system issue.

**Comment by Angela** [comment]
Hi @malte0811. Thanks for your report! I've uploaded a new version 1.4.1. Can you try that and let me know whether it fixes the crash for you?

**Comment by malte0811** [comment]
I didn't get the crash myself, @brisingraerowing mentioned a weird crash and I didn't have anything better to do than looking into it. The new file looks like it should be fine (doesn't have SweetConcrete classes), so I'll close this.

**Comment by brisingraerowing** [comment]
I'll test the new file when I get to my computer. Might be a bit.
